// GERADO por scripts/gerar-cnae-catalogo.mjs — não edite à mão.
// Fonte: IBGE, https://servicodados.ibge.gov.br/api/v2/cnae
// 87 divisões (2 dígitos) + 673 classes (5 dígitos, com verificador).

/** `[código só com dígitos, descrição]`. 2 dígitos = divisão; 5 = classe. */
export type EntradaCnae = readonly [codigo: string, descricao: string];

export const CNAE_CATALOGO: readonly EntradaCnae[] = [
  ["01", "Agricultura, Pecuária e Serviços Relacionados"],
  ["01113", "Cultivo de Cereais"],
  ["01121", "Cultivo de Algodão Herbáceo e de Outras Fibras de Lavoura Temporária"],
  ["01130", "Cultivo de Cana-de-Açúcar"],
  ["01148", "Cultivo de Fumo"],
  ["01156", "Cultivo de Soja"],
  ["01164", "Cultivo de Oleaginosas de Lavoura Temporária, Exceto Soja"],
  ["01199", "Cultivo de Plantas de Lavoura Temporária Não Especificadas Anteriormente"],
  ["01211", "Horticultura"],
  ["01229", "Cultivo de Flores e Plantas Ornamentais"],
  ["01318", "Cultivo de Laranja"],
  ["01326", "Cultivo de Uva"],
  ["01334", "Cultivo de Frutas de Lavoura Permanente, Exceto Laranja e Uva"],
  ["01342", "Cultivo de Café"],
  ["01351", "Cultivo de Cacau"],
  ["01393", "Cultivo de Plantas de Lavoura Permanente Não Especificadas Anteriormente"],
  ["01415", "Produção de Sementes Certificadas"],
  ["01423", "Produção de Mudas e Outras Formas de Propagação Vegetal, Certificadas"],
  ["01512", "Criação de Bovinos"],
  ["01521", "Criação de Outros Animais de Grande Porte"],
  ["01539", "Criação de Caprinos e Ovinos"],
  ["01547", "Criação de Suínos"],
  ["01555", "Criação de Aves"],
  ["01598", "Criação de Animais Não Especificados Anteriormente"],
  ["01610", "Atividades de Apoio À Agricultura"],
  ["01628", "Atividades de Apoio À Pecuária"],
  ["01636", "Atividades de Pós-Colheita"],
  ["01709", "Caça e Serviços Relacionados"],
  ["02", "Produção Florestal"],
  ["02101", "Produção Florestal - Florestas Plantadas"],
  ["02209", "Produção Florestal - Florestas Nativas"],
  ["02306", "Atividades de Apoio À Produção Florestal"],
  ["03", "Pesca e Aqüicultura"],
  ["03116", "Pesca em Água Salgada"],
  ["03124", "Pesca em Água Doce"],
  ["03213", "Aquicultura em Água Salgada e Salobra"],
  ["03221", "Aquicultura em Água Doce"],
  ["05", "Extração de Carvão Mineral"],
  ["05003", "Extração de Carvão Mineral"],
  ["06", "Extração de Petróleo e Gás Natural"],
  ["06000", "Extração de Petróleo e Gás Natural"],
  ["07", "Extração de Minerais Metálicos"],
  ["07103", "Extração de Minério de Ferro"],
  ["07219", "Extração de Minério de Alumínio"],
  ["07227", "Extração de Minério de Estanho"],
  ["07235", "Extração de Minério de Manganês"],
  ["07243", "Extração de Minério de Metais Preciosos"],
  ["07251", "Extração de Minerais Radioativos"],
  ["07294", "Extração de Minerais Metálicos Não Ferrosos Não Especificados Anteriormente"],
  ["08", "Extração de Minerais Não-Metálicos"],
  ["08100", "Extração de Pedra, Areia e Argila"],
  ["08916", "Extração de Minerais para Fabricação de Adubos, Fertilizantes e Outros Produtos Químicos"],
  ["08924", "Extração e Refino de Sal Marinho e Sal-Gema"],
  ["08932", "Extração de Gemas (pedras Preciosas e Semipreciosas)"],
  ["08991", "Extração de Minerais Não Metálicos Não Especificados Anteriormente"],
  ["09", "Atividades de Apoio À Extração de Minerais"],
  ["09106", "Atividades de Apoio À Extração de Petróleo e Gás Natural"],
  ["09904", "Atividades de Apoio À Extração de Minerais, Exceto Petróleo e Gás Natural"],
  ["10", "Fabricação de Produtos Alimentícios"],
  ["10112", "Abate de Reses, Exceto Suínos"],
  ["10121", "Abate de Suínos, Aves e Outros Pequenos Animais"],
  ["10139", "Fabricação de Produtos de Carne"],
  ["10201", "Preservação do Pescado e Fabricação de Produtos do Pescado"],
  ["10317", "Fabricação de Conservas de Frutas"],
  ["10325", "Fabricação de Conservas de Legumes e Outros Vegetais"],
  ["10333", "Fabricação de Sucos de Frutas, Hortaliças e Legumes"],
  ["10414", "Fabricação de Óleos Vegetais em Bruto, Exceto Óleo de Milho"],
  ["10422", "Fabricação de Óleos Vegetais Refinados, Exceto Óleo de Milho"],
  ["10431", "Fabricação de Margarina e Outras Gorduras Vegetais e de Óleos Não Comestíveis de Animais"],
  ["10511", "Preparação do Leite"],
  ["10520", "Fabricação de Laticínios"],
  ["10538", "Fabricação de Sorvetes e Outros Gelados Comestíveis"],
  ["10619", "Beneficiamento de Arroz e Fabricação de Produtos do Arroz"],
  ["10627", "Moagem de Trigo e Fabricação de Derivados"],
  ["10635", "Fabricação de Farinha de Mandioca e Derivados"],
  ["10643", "Fabricação de Farinha de Milho e Derivados, Exceto Óleos de Milho"],
  ["10651", "Fabricação de Amidos e Féculas de Vegetais e de Óleos de Milho"],
  ["10660", "Fabricação de Alimentos para Animais"],
  ["10694", "Moagem e Fabricação de Produtos de Origem Vegetal Não Especificados Anteriormente"],
  ["10716", "Fabricação de Açúcar em Bruto"],
  ["10724", "Fabricação de Açúcar Refinado"],
  ["10813", "Torrefação e Moagem de Café"],
  ["10821", "Fabricação de Produtos À Base de Café"],
  ["10911", "Fabricação de Produtos de Panificação"],
  ["10929", "Fabricação de Biscoitos e Bolachas"],
  ["10937", "Fabricação de Produtos Derivados do Cacau, de Chocolates e Confeitos"],
  ["10945", "Fabricação de Massas Alimentícias"],
  ["10953", "Fabricação de Especiarias, Molhos, Temperos e Condimentos"],
  ["10961", "Fabricação de Alimentos e Pratos Prontos"],
  ["10996", "Fabricação de Produtos Alimentícios Não Especificados Anteriormente"],
  ["11", "Fabricação de Bebidas"],
  ["11119", "Fabricação de Aguardentes e Outras Bebidas Destiladas"],
  ["11127", "Fabricação de Vinho"],
  ["11135", "Fabricação de Malte, Cervejas e Chopes"],
  ["11216", "Fabricação de Águas Envasadas"],
  ["11224", "Fabricação de Refrigerantes e de Outras Bebidas Não Alcoólicas"],
  ["12", "Fabricação de Produtos do Fumo"],
  ["12107", "Processamento Industrial do Fumo"],
  ["12204", "Fabricação de Produtos do Fumo"],
  ["13", "Fabricação de Produtos Têxteis"],
  ["13111", "Preparação e Fiação de Fibras de Algodão"],
  ["13120", "Preparação e Fiação de Fibras Têxteis Naturais, Exceto Algodão"],
  ["13138", "Fiação de Fibras Artificiais e Sintéticas"],
  ["13146", "Fabricação de Linhas para Costurar e Bordar"],
  ["13219", "Tecelagem de Fios de Algodão"],
  ["13227", "Tecelagem de Fios de Fibras Têxteis Naturais, Exceto Algodão"],
  ["13235", "Tecelagem de Fios de Fibras Artificiais e Sintéticas"],
  ["13308", "Fabricação de Tecidos de Malha"],
  ["13405", "Acabamentos em Fios, Tecidos e Artefatos Têxteis"],
  ["13511", "Fabricação de Artefatos Têxteis para Uso Doméstico"],
  ["13529", "Fabricação de Artefatos de Tapeçaria"],
  ["13537", "Fabricação de Artefatos de Cordoaria"],
  ["13545", "Fabricação de Tecidos Especiais, Inclusive Artefatos"],
  ["13596", "Fabricação de Outros Produtos Têxteis Não Especificados Anteriormente"],
  ["14", "Confecção de Artigos do Vestuário e Acessórios"],
  ["14118", "Confecção de Roupas Íntimas"],
  ["14126", "Confecção de Peças de Vestuário, Exceto Roupas Íntimas"],
  ["14134", "Confecção de Roupas Profissionais"],
  ["14142", "Fabricação de Acessórios do Vestuário, Exceto para Segurança e Proteção"],
  ["14215", "Fabricação de Meias"],
  ["14223", "Fabricação de Artigos do Vestuário, Produzidos em Malharias e Tricotagens, Exceto Meias"],
  ["15", "Preparação de Couros e Fabricação de Artefatos de Couro, Artigos para Viagem e Calçados"],
  ["15106", "Curtimento e Outras Preparações de Couro"],
  ["15211", "Fabricação de Artigos para Viagem, Bolsas e Semelhantes de Qualquer Material"],
  ["15297", "Fabricação de Artefatos de Couro Não Especificados Anteriormente"],
  ["15319", "Fabricação de Calçados de Couro"],
  ["15327", "Fabricação de Tênis de Qualquer Material"],
  ["15335", "Fabricação de Calçados de Material Sintético"],
  ["15394", "Fabricação de Calçados de Materiais Não Especificados Anteriormente"],
  ["15408", "Fabricação de Partes para Calçados, de Qualquer Material"],
  ["16", "Fabricação de Produtos de Madeira"],
  ["16102", "Desdobramento de Madeira"],
  ["16218", "Fabricação de Madeira Laminada e de Chapas de Madeira Compensada, Prensada e Aglomerada"],
  ["16226", "Fabricação de Estruturas de Madeira e de Artigos de Carpintaria para Construção"],
  ["16234", "Fabricação de Artefatos de Tanoaria e de Embalagens de Madeira"],
  ["16293", "Fabricação de Artefatos de Madeira, Palha, Cortiça, Vime e Material Trançado Não Especificados Anteriormente, Exceto Móveis"],
  ["17", "Fabricação de Celulose, Papel e Produtos de Papel"],
  ["17109", "Fabricação de Celulose e Outras Pastas para a Fabricação de Papel"],
  ["17214", "Fabricação de Papel"],
  ["17222", "Fabricação de Cartolina e Papel-Cartão"],
  ["17311", "Fabricação de Embalagens de Papel"],
  ["17320", "Fabricação de Embalagens de Cartolina e Papel-Cartão"],
  ["17338", "Fabricação de Chapas e de Embalagens de Papelão Ondulado"],
  ["17419", "Fabricação de Produtos de Papel, Cartolina, Papel Cartão e Papelão Ondulado para Uso Comercial e de Escritório"],
  ["17427", "Fabricação de Produtos de Papel para Usos Doméstico e Higiênico-Sanitário"],
  ["17494", "Fabricação de Produtos de Pastas Celulósicas, Papel, Cartolina, Papel-Cartão e Papelão Ondulado Não Especificados Anteriormente"],
  ["18", "Impressão e Reprodução de Gravações"],
  ["18113", "Impressão de Jornais, Livros, Revistas e Outras Publicações Periódicas"],
  ["18121", "Impressão de Material de Segurança"],
  ["18130", "Impressão de Materiais para Outros Usos"],
  ["18211", "Serviços de Pré-Impressão"],
  ["18229", "Serviços de Acabamentos Gráficos"],
  ["18300", "Reprodução de Materiais Gravados em Qualquer Suporte"],
  ["19", "Fabricação de Coque, de Produtos Derivados do Petróleo e de Biocombustíveis"],
  ["19101", "Coquerias"],
  ["19217", "Fabricação de Produtos do Refino de Petróleo"],
  ["19225", "Fabricação de Produtos Derivados do Petróleo, Exceto Produtos do Refino"],
  ["19314", "Fabricação de Álcool"],
  ["19322", "Fabricação de Biocombustíveis, Exceto Álcool"],
  ["20", "Fabricação de Produtos Químicos"],
  ["20118", "Fabricação de Cloro e Álcalis"],
  ["20126", "Fabricação de Intermediários para Fertilizantes"],
  ["20134", "Fabricação de Adubos e Fertilizantes"],
  ["20142", "Fabricação de Gases Industriais"],
  ["20193", "Fabricação de Produtos Químicos Inorgânicos Não Especificados Anteriormente"],
  ["20215", "Fabricação de Produtos Petroquímicos Básicos"],
  ["20223", "Fabricação de Intermediários para Plastificantes, Resinas e Fibras"],
  ["20291", "Fabricação de Produtos Químicos Orgânicos Não Especificados Anteriormente"],
  ["20312", "Fabricação de Resinas Termoplásticas"],
  ["20321", "Fabricação de Resinas Termofixas"],
  ["20339", "Fabricação de Elastômeros"],
  ["20401", "Fabricação de Fibras Artificiais e Sintéticas"],
  ["20517", "Fabricação de Defensivos Agrícolas"],
  ["20525", "Fabricação de Desinfestantes Domissanitários"],
  ["20614", "Fabricação de Sabões e Detergentes Sintéticos"],
  ["20622", "Fabricação de Produtos de Limpeza e Polimento"],
  ["20631", "Fabricação de Cosméticos, Produtos de Perfumaria e de Higiene Pessoal"],
  ["20711", "Fabricação de Tintas, Vernizes, Esmaltes e Lacas"],
  ["20720", "Fabricação de Tintas de Impressão"],
  ["20738", "Fabricação de Impermeabilizantes, Solventes e Produtos Afins"],
  ["20916", "Fabricação de Adesivos e Selantes"],
  ["20924", "Fabricação de Explosivos"],
  ["20932", "Fabricação de Aditivos de Uso Industrial"],
  ["20941", "Fabricação de Catalisadores"],
  ["20991", "Fabricação de Produtos Químicos Não Especificados Anteriormente"],
  ["21", "Fabricação de Produtos Farmoquímicos e Farmacêuticos"],
  ["21106", "Fabricação de Produtos Farmoquímicos"],
  ["21211", "Fabricação de Medicamentos para Uso Humano"],
  ["21220", "Fabricação de Medicamentos para Uso Veterinário"],
  ["21238", "Fabricação de Preparações Farmacêuticas"],
  ["22", "Fabricação de Produtos de Borracha e de Material Plástico"],
  ["22111", "Fabricação de Pneumáticos e de Câmaras-de-Ar"],
  ["22129", "Reforma de Pneumáticos Usados"],
  ["22196", "Fabricação de Artefatos de Borracha Não Especificados Anteriormente"],
  ["22218", "Fabricação de Laminados Planos e Tubulares de Material Plástico"],
  ["22226", "Fabricação de Embalagens de Material Plástico"],
  ["22234", "Fabricação de Tubos e Acessórios de Material Plástico para Uso na Construção"],
  ["22293", "Fabricação de Artefatos de Material Plástico Não Especificados Anteriormente"],
  ["23", "Fabricação de Produtos de Minerais Não-Metálicos"],
  ["23117", "Fabricação de Vidro Plano e de Segurança"],
  ["23125", "Fabricação de Embalagens de Vidro"],
  ["23192", "Fabricação de Artigos de Vidro"],
  ["23206", "Fabricação de Cimento"],
  ["23303", "Fabricação de Artefatos de Concreto, Cimento, Fibrocimento, Gesso e Materiais Semelhantes"],
  ["23419", "Fabricação de Produtos Cerâmicos Refratários"],
  ["23427", "Fabricação de Produtos Cerâmicos Não Refratários para Uso Estrutural na Construção"],
  ["23494", "Fabricação de Produtos Cerâmicos Não Refratários Não Especificados Anteriormente"],
  ["23915", "Aparelhamento e Outros Trabalhos em Pedras"],
  ["23923", "Fabricação de Cal e Gesso"],
  ["23991", "Fabricação de Produtos de Minerais Não Metálicos Não Especificados Anteriormente"],
  ["24", "Metalurgia"],
  ["24113", "Produção de Ferro-Gusa"],
  ["24121", "Produção de Ferroligas"],
  ["24211", "Produção de Semiacabados de Aço"],
  ["24229", "Produção de Laminados Planos de Aço"],
  ["24237", "Produção de Laminados Longos de Aço"],
  ["24245", "Produção de Relaminados, Trefilados e Perfilados de Aço"],
  ["24318", "Produção de Tubos de Aço com Costura"],
  ["24393", "Produção de Outros Tubos de Ferro e Aço"],
  ["24415", "Metalurgia do Alumínio e Suas Ligas"],
  ["24423", "Metalurgia dos Metais Preciosos"],
  ["24431", "Metalurgia do Cobre"],
  ["24491", "Metalurgia dos Metais Não Ferrosos e Suas Ligas Não Especificados Anteriormente"],
  ["24512", "Fundição de Ferro e Aço"],
  ["24521", "Fundição de Metais Não Ferrosos e Suas Ligas"],
  ["25", "Fabricação de Produtos de Metal, Exceto Máquinas e Equipamentos"],
  ["25110", "Fabricação de Estruturas Metálicas"],
  ["25128", "Fabricação de Esquadrias de Metal"],
  ["25136", "Fabricação de Obras de Caldeiraria Pesada"],
  ["25217", "Fabricação de Tanques, Reservatórios Metálicos e Caldeiras para Aquecimento Central"],
  ["25225", "Fabricação de Caldeiras Geradoras de Vapor, Exceto para Aquecimento Central e para Veículos"],
  ["25314", "Produção de Forjados de Aço e de Metais Não Ferrosos e Suas Ligas"],
  ["25322", "Produção de Artefatos Estampados de Metal; Metalurgia do Pó"],
  ["25390", "Serviços de Usinagem, Solda, Tratamento e Revestimento em Metais"],
  ["25411", "Fabricação de Artigos de Cutelaria"],
  ["25420", "Fabricação de Artigos de Serralheria, Exceto Esquadrias"],
  ["25438", "Fabricação de Ferramentas"],
  ["25501", "Fabricação de Equipamento Bélico Pesado, Armas e Munições"],
  ["25918", "Fabricação de Embalagens Metálicas"],
  ["25926", "Fabricação de Produtos de Trefilados de Metal"],
  ["25934", "Fabricação de Artigos de Metal para Uso Doméstico e Pessoal"],
  ["25993", "Fabricação de Produtos de Metal Não Especificados Anteriormente"],
  ["26", "Fabricação de Equipamentos de Informática, Produtos Eletrônicos e Ópticos"],
  ["26108", "Fabricação de Componentes Eletrônicos"],
  ["26213", "Fabricação de Equipamentos de Informática"],
  ["26221", "Fabricação de Periféricos para Equipamentos de Informática"],
  ["26311", "Fabricação de Equipamentos Transmissores de Comunicação"],
  ["26329", "Fabricação de Aparelhos Telefônicos e de Outros Equipamentos de Comunicação"],
  ["26400", "Fabricação de Aparelhos de Recepção, Reprodução, Gravação e Amplificação de Áudio e Vídeo"],
  ["26515", "Fabricação de Aparelhos e Equipamentos de Medida, Teste e Controle"],
  ["26523", "Fabricação de Cronômetros e Relógios"],
  ["26604", "Fabricação de Aparelhos Eletromédicos e Eletroterapêuticos e Equipamentos de Irradiação"],
  ["26701", "Fabricação de Equipamentos e Instrumentos Ópticos, Fotográficos e Cinematográficos"],
  ["26809", "Fabricação de Mídias Virgens, Magnéticas e Ópticas"],
  ["27", "Fabricação de Máquinas, Aparelhos e Materiais Elétricos"],
  ["27104", "Fabricação de Geradores, Transformadores e Motores Elétricos"],
  ["27210", "Fabricação de Pilhas, Baterias e Acumuladores Elétricos, Exceto para Veículos Automotores"],
  ["27228", "Fabricação de Baterias e Acumuladores para Veículos Automotores"],
  ["27317", "Fabricação de Aparelhos e Equipamentos para Distribuição e Controle de Energia Elétrica"],
  ["27325", "Fabricação de Material Elétrico para Instalações em Circuito de Consumo"],
  ["27333", "Fabricação de Fios, Cabos e Condutores Elétricos Isolados"],
  ["27406", "Fabricação de Lâmpadas e Outros Equipamentos de Iluminação"],
  ["27511", "Fabricação de Fogões, Refrigeradores e Máquinas de Lavar e Secar para Uso Doméstico"],
  ["27597", "Fabricação de Aparelhos Eletrodomésticos Não Especificados Anteriormente"],
  ["27902", "Fabricação de Equipamentos e Aparelhos Elétricos Não Especificados Anteriormente"],
  ["28", "Fabricação de Máquinas e Equipamentos"],
  ["28119", "Fabricação de Motores e Turbinas, Exceto para Aviões e Veículos Rodoviários"],
  ["28127", "Fabricação de Equipamentos Hidráulicos e Pneumáticos, Exceto Válvulas"],
  ["28135", "Fabricação de Válvulas, Registros e Dispositivos Semelhantes"],
  ["28143", "Fabricação de Compressores"],
  ["28151", "Fabricação de Equipamentos de Transmissão para Fins Industriais"],
  ["28216", "Fabricação de Aparelhos e Equipamentos para Instalações Térmicas"],
  ["28224", "Fabricação de Máquinas, Equipamentos e Aparelhos para Transporte e Elevação de Cargas e Pessoas"],
  ["28232", "Fabricação de Máquinas e Aparelhos de Refrigeração e Ventilação para Uso Industrial e Comercial"],
  ["28241", "Fabricação de Aparelhos e Equipamentos de Ar Condicionado"],
  ["28259", "Fabricação de Máquinas e Equipamentos para Saneamento Básico e Ambiental"],
  ["28291", "Fabricação de Máquinas e Equipamentos de Uso Geral Não Especificados Anteriormente"],
  ["28313", "Fabricação de Tratores Agrícolas"],
  ["28321", "Fabricação de Equipamentos para Irrigação Agrícola"],
  ["28330", "Fabricação de Máquinas e Equipamentos para a Agricultura e Pecuária, Exceto para Irrigação"],
  ["28402", "Fabricação de Máquinas-Ferramenta"],
  ["28518", "Fabricação de Máquinas e Equipamentos para a Prospecção e Extração de Petróleo"],
  ["28526", "Fabricação de Outras Máquinas e Equipamentos para Uso na Extração Mineral, Exceto na Extração de Petróleo"],
  ["28534", "Fabricação de Tratores, Exceto Agrícolas"],
  ["28542", "Fabricação de Máquinas e Equipamentos para Terraplenagem, Pavimentação e Construção, Exceto Tratores"],
  ["28615", "Fabricação de Máquinas para a Indústria Metalúrgica, Exceto Máquinas-Ferramenta"],
  ["28623", "Fabricação de Máquinas e Equipamentos para as Indústrias de Alimentos, Bebidas e Fumo"],
  ["28631", "Fabricação de Máquinas e Equipamentos para a Indústria Têxtil"],
  ["28640", "Fabricação de Máquinas e Equipamentos para as Indústrias do Vestuário, do Couro e de Calçados"],
  ["28658", "Fabricação de Máquinas e Equipamentos para as Indústrias de Celulose, Papel e Papelão e Artefatos"],
  ["28666", "Fabricação de Máquinas e Equipamentos para a Indústria do Plástico"],
  ["28691", "Fabricação de Máquinas e Equipamentos para Uso Industrial Específico Não Especificados Anteriormente"],
  ["29", "Fabricação de Veículos Automotores, Reboques e Carrocerias"],
  ["29107", "Fabricação de Automóveis, Camionetas e Utilitários"],
  ["29204", "Fabricação de Caminhões e Ônibus"],
  ["29301", "Fabricação de Cabines, Carrocerias e Reboques para Veículos Automotores"],
  ["29417", "Fabricação de Peças e Acessórios para o Sistema Motor de Veículos Automotores"],
  ["29425", "Fabricação de Peças e Acessórios para os Sistemas de Marcha e Transmissão de Veículos Automotores"],
  ["29433", "Fabricação de Peças e Acessórios para o Sistema de Freios de Veículos Automotores"],
  ["29441", "Fabricação de Peças e Acessórios para o Sistema de Direção e Suspensão de Veículos Automotores"],
  ["29450", "Fabricação de Material Elétrico e Eletrônico para Veículos Automotores, Exceto Baterias"],
  ["29492", "Fabricação de Peças e Acessórios para Veículos Automotores Não Especificados Anteriormente"],
  ["29506", "Recondicionamento e Recuperação de Motores para Veículos Automotores"],
  ["30", "Fabricação de Outros Equipamentos de Transporte, Exceto Veículos Automotores"],
  ["30113", "Construção de Embarcações e Estruturas Flutuantes"],
  ["30121", "Construção de Embarcações para Esporte e Lazer"],
  ["30318", "Fabricação de Locomotivas, Vagões e Outros Materiais Rodantes"],
  ["30326", "Fabricação de Peças e Acessórios para Veículos Ferroviários"],
  ["30415", "Fabricação de Aeronaves"],
  ["30423", "Fabricação de Turbinas, Motores e Outros Componentes e Peças para Aeronaves"],
  ["30504", "Fabricação de Veículos Militares de Combate"],
  ["30911", "Fabricação de Motocicletas"],
  ["30920", "Fabricação de Bicicletas e Triciclos Não Motorizados"],
  ["30997", "Fabricação de Equipamentos de Transporte Não Especificados Anteriormente"],
  ["31", "Fabricação de Móveis"],
  ["31012", "Fabricação de Móveis com Predominância de Madeira"],
  ["31021", "Fabricação de Móveis com Predominância de Metal"],
  ["31039", "Fabricação de Móveis de Outros Materiais, Exceto Madeira e Metal"],
  ["31047", "Fabricação de Colchões"],
  ["32", "Fabricação de Produtos Diversos"],
  ["32116", "Lapidação de Gemas e Fabricação de Artefatos de Ourivesaria e Joalheria"],
  ["32124", "Fabricação de Bijuterias e Artefatos Semelhantes"],
  ["32205", "Fabricação de Instrumentos Musicais"],
  ["32302", "Fabricação de Artefatos para Pesca e Esporte"],
  ["32400", "Fabricação de Brinquedos e Jogos Recreativos"],
  ["32507", "Fabricação de Instrumentos e Materiais para Uso Médico e Odontológico e de Artigos Ópticos"],
  ["32914", "Fabricação de Escovas, Pincéis e Vassouras"],
  ["32922", "Fabricação de Equipamentos e Acessórios para Segurança e Proteção Pessoal e Profissional"],
  ["32990", "Fabricação de Produtos Diversos Não Especificados Anteriormente"],
  ["33", "Manutenção, Reparação e Instalação de Máquinas e Equipamentos"],
  ["33112", "Manutenção e Reparação de Tanques, Reservatórios Metálicos e Caldeiras, Exceto para Veículos"],
  ["33121", "Manutenção e Reparação de Equipamentos Eletrônicos e Ópticos"],
  ["33139", "Manutenção e Reparação de Máquinas e Equipamentos Elétricos"],
  ["33147", "Manutenção e Reparação de Máquinas e Equipamentos da Indústria Mecânica"],
  ["33155", "Manutenção e Reparação de Veículos Ferroviários"],
  ["33163", "Manutenção e Reparação de Aeronaves"],
  ["33171", "Manutenção e Reparação de Embarcações"],
  ["33198", "Manutenção e Reparação de Equipamentos e Produtos Não Especificados Anteriormente"],
  ["33210", "Instalação de Máquinas e Equipamentos Industriais"],
  ["33295", "Instalação de Equipamentos Não Especificados Anteriormente"],
  ["35", "Eletricidade, Gás e Outras Utilidades"],
  ["35115", "Geração de Energia Elétrica"],
  ["35123", "Transmissão de Energia Elétrica"],
  ["35131", "Comércio Atacadista de Energia Elétrica"],
  ["35140", "Distribuição de Energia Elétrica"],
  ["35204", "Produção de Gás; Processamento de Gás Natural; Distribuição de Combustíveis Gasosos por Redes Urbanas"],
  ["35301", "Produção e Distribuição de Vapor, Água Quente e Ar Condicionado"],
  ["36", "Captação, Tratamento e Distribuição de Água"],
  ["36006", "Captação, Tratamento e Distribuição de Água"],
  ["37", "Esgoto e Atividades Relacionadas"],
  ["37011", "Gestão de Redes de Esgoto"],
  ["37029", "Atividades Relacionadas a Esgoto, Exceto a Gestão de Redes"],
  ["38", "Coleta, Tratamento e Disposição de Resíduos; Recuperação de Materiais"],
  ["38114", "Coleta de Resíduos Não Perigosos"],
  ["38122", "Coleta de Resíduos Perigosos"],
  ["38211", "Tratamento e Disposição de Resíduos Não Perigosos"],
  ["38220", "Tratamento e Disposição de Resíduos Perigosos"],
  ["38319", "Recuperação de Materiais Metálicos"],
  ["38327", "Recuperação de Materiais Plásticos"],
  ["38394", "Recuperação de Materiais Não Especificados Anteriormente"],
  ["39", "Descontaminação e Outros Serviços de Gestão de Resíduos"],
  ["39005", "Descontaminação e Outros Serviços de Gestão de Resíduos"],
  ["41", "Construção de Edifícios"],
  ["41107", "Incorporação de Empreendimentos Imobiliários"],
  ["41204", "Construção de Edifícios"],
  ["42", "Obras de Infra-Estrutura"],
  ["42111", "Construção de Rodovias e Ferrovias"],
  ["42120", "Construção de Obras de Arte Especiais"],
  ["42138", "Obras de Urbanização - Ruas, Praças e Calçadas"],
  ["42219", "Obras para Geração e Distribuição de Energia Elétrica e para Telecomunicações"],
  ["42227", "Construção de Redes de Abastecimento de Água, Coleta de Esgoto e Construções Correlatas"],
  ["42235", "Construção de Redes de Transportes por Dutos, Exceto para Água e Esgoto"],
  ["42910", "Obras Portuárias, Marítimas e Fluviais"],
  ["42928", "Montagem de Instalações Industriais e de Estruturas Metálicas"],
  ["42995", "Obras de Engenharia Civil Não Especificadas Anteriormente"],
  ["43", "Serviços Especializados para Construção"],
  ["43118", "Demolição e Preparação de Canteiros de Obras"],
  ["43126", "Perfurações e Sondagens"],
  ["43134", "Obras de Terraplenagem"],
  ["43193", "Serviços de Preparação do Terreno Não Especificados Anteriormente"],
  ["43215", "Instalações Elétricas"],
  ["43223", "Instalações Hidráulicas, de Sistemas de Ventilação e Refrigeração"],
  ["43291", "Obras de Instalações em Construções Não Especificadas Anteriormente"],
  ["43304", "Obras de Acabamento"],
  ["43916", "Obras de Fundações"],
  ["43991", "Serviços Especializados para Construção Não Especificados Anteriormente"],
  ["45", "Comércio e Reparação de Veículos Automotores e Motocicletas"],
  ["45111", "Comércio a Varejo e por Atacado de Veículos Automotores"],
  ["45129", "Representantes Comerciais e Agentes do Comércio de Veículos Automotores"],
  ["45200", "Manutenção e Reparação de Veículos Automotores"],
  ["45307", "Comércio de Peças e Acessórios para Veículos Automotores"],
  ["45412", "Comércio por Atacado e a Varejo de Motocicletas, Peças e Acessórios"],
  ["45421", "Representantes Comerciais e Agentes do Comércio de Motocicletas, Peças e Acessórios"],
  ["45439", "Manutenção e Reparação de Motocicletas"],
  ["46", "Comércio por Atacado, Exceto Veículos Automotores e Motocicletas"],
  ["46117", "Representantes Comerciais e Agentes do Comércio de Matérias-Primas Agrícolas e Animais Vivos"],
  ["46125", "Representantes Comerciais e Agentes do Comércio de Combustíveis, Minerais, Produtos Siderúrgicos e Químicos"],
  ["46133", "Representantes Comerciais e Agentes do Comércio de Madeira, Material de Construção e Ferragens"],
  ["46141", "Representantes Comerciais e Agentes do Comércio de Máquinas, Equipamentos, Embarcações e Aeronaves"],
  ["46150", "Representantes Comerciais e Agentes do Comércio de Eletrodomésticos, Móveis e Artigos de Uso Doméstico"],
  ["46168", "Representantes Comerciais e Agentes do Comércio de Têxteis, Vestuário, Calçados e Artigos de Viagem"],
  ["46176", "Representantes Comerciais e Agentes do Comércio de Produtos Alimentícios, Bebidas e Fumo"],
  ["46184", "Representantes Comerciais e Agentes do Comércio Especializado em Produtos Não Especificados Anteriormente"],
  ["46192", "Representantes Comerciais e Agentes do Comércio de Mercadorias em Geral Não Especializado"],
  ["46214", "Comércio Atacadista de Café em Grão"],
  ["46222", "Comércio Atacadista de Soja"],
  ["46231", "Comércio Atacadista de Animais Vivos, Alimentos para Animais e Matérias-Primas Agrícolas, Exceto Café e Soja"],
  ["46311", "Comércio Atacadista de Leite e Laticínios"],
  ["46320", "Comércio Atacadista de Cereais e Leguminosas Beneficiados, Farinhas, Amidos e Féculas"],
  ["46338", "Comércio Atacadista de Hortifrutigranjeiros"],
  ["46346", "Comércio Atacadista de Carnes, Produtos da Carne e Pescado"],
  ["46354", "Comércio Atacadista de Bebidas"],
  ["46362", "Comércio Atacadista de Produtos do Fumo"],
  ["46371", "Comércio Atacadista Especializado em Produtos Alimentícios Não Especificados Anteriormente"],
  ["46397", "Comércio Atacadista de Produtos Alimentícios em Geral"],
  ["46419", "Comércio Atacadista de Tecidos, Artefatos de Tecidos e de Armarinho"],
  ["46427", "Comércio Atacadista de Artigos do Vestuário e Acessórios"],
  ["46435", "Comércio Atacadista de Calçados e Artigos de Viagem"],
  ["46443", "Comércio Atacadista de Produtos Farmacêuticos para Uso Humano e Veterinário"],
  ["46451", "Comércio Atacadista de Instrumentos e Materiais para Uso Médico, Cirúrgico, Ortopédico e Odontológico"],
  ["46460", "Comércio Atacadista de Cosméticos, Produtos de Perfumaria e de Higiene Pessoal"],
  ["46478", "Comércio Atacadista de Artigos de Escritório e de Papelaria; Livros, Jornais e Outras Publicações"],
  ["46494", "Comércio Atacadista de Equipamentos e Artigos de Uso Pessoal e Doméstico Não Especificados Anteriormente"],
  ["46516", "Comércio Atacadista de Computadores, Periféricos e Suprimentos de Informática"],
  ["46524", "Comércio Atacadista de Componentes Eletrônicos e Equipamentos de Telefonia e Comunicação"],
  ["46613", "Comércio Atacadista de Máquinas, Aparelhos e Equipamentos para Uso Agropecuário; Partes e Peças"],
  ["46621", "Comércio Atacadista de Máquinas, Equipamentos para Terraplenagem, Mineração e Construção; Partes e Peças"],
  ["46630", "Comércio Atacadista de Máquinas e Equipamentos para Uso Industrial; Partes e Peças"],
  ["46648", "Comércio Atacadista de Máquinas, Aparelhos e Equipamentos para Uso Odonto-Médico-Hospitalar; Partes e Peças"],
  ["46656", "Comércio Atacadista de Máquinas e Equipamentos para Uso Comercial; Partes e Peças"],
  ["46699", "Comércio Atacadista de Máquinas, Aparelhos e Equipamentos Não Especificados Anteriormente; Partes e Peças"],
  ["46711", "Comércio Atacadista de Madeira e Produtos Derivados"],
  ["46729", "Comércio Atacadista de Ferragens e Ferramentas"],
  ["46737", "Comércio Atacadista de Material Elétrico"],
  ["46745", "Comércio Atacadista de Cimento"],
  ["46796", "Comércio Atacadista Especializado de Materiais de Construção Não Especificados Anteriormente e de Materiais de Construção em Geral"],
  ["46818", "Comércio Atacadista de Combustíveis Sólidos, Líquidos e Gasosos, Exceto Gás Natural e GLP"],
  ["46826", "Comércio Atacadista de Gás Liquefeito de Petróleo (glp)"],
  ["46834", "Comércio Atacadista de Defensivos Agrícolas, Adubos, Fertilizantes e Corretivos do Solo"],
  ["46842", "Comércio Atacadista de Produtos Químicos e Petroquímicos, Exceto Agroquímicos"],
  ["46851", "Comércio Atacadista de Produtos Siderúrgicos e Metalúrgicos, Exceto para Construção"],
  ["46869", "Comércio Atacadista de Papel e Papelão em Bruto e de Embalagens"],
  ["46877", "Comércio Atacadista de Resíduos e Sucatas"],
  ["46893", "Comércio Atacadista Especializado de Outros Produtos Intermediários Não Especificados Anteriormente"],
  ["46915", "Comércio Atacadista de Mercadorias em Geral, com Predominância de Produtos Alimentícios"],
  ["46923", "Comércio Atacadista de Mercadorias em Geral, com Predominância de Insumos Agropecuários"],
  ["46931", "Comércio Atacadista de Mercadorias em Geral, sem Predominância de Alimentos ou de Insumos Agropecuários"],
  ["47", "Comércio Varejista"],
  ["47113", "Comércio Varejista de Mercadorias em Geral, com Predominância de Produtos Alimentícios - Hipermercados e Supermercados"],
  ["47121", "Comércio Varejista de Mercadorias em Geral, com Predominância de Produtos Alimentícios - Minimercados, Mercearias e Armazéns"],
  ["47130", "Comércio Varejista de Mercadorias em Geral, sem Predominância de Produtos Alimentícios"],
  ["47211", "Comércio Varejista de Produtos de Padaria, Laticínio, Doces, Balas e Semelhantes"],
  ["47229", "Comércio Varejista de Carnes e Pescados - Açougues e Peixarias"],
  ["47237", "Comércio Varejista de Bebidas"],
  ["47245", "Comércio Varejista de Hortifrutigranjeiros"],
  ["47296", "Comércio Varejista de Produtos Alimentícios em Geral ou Especializado em Produtos Alimentícios Não Especificados Anteriormente; Produtos do Fumo"],
  ["47318", "Comércio Varejista de Combustíveis para Veículos Automotores"],
  ["47326", "Comércio Varejista de Lubrificantes"],
  ["47415", "Comércio Varejista de Tintas e Materiais para Pintura"],
  ["47423", "Comércio Varejista de Material Elétrico"],
  ["47431", "Comércio Varejista de Vidros"],
  ["47440", "Comércio Varejista de Ferragens, Madeira e Materiais de Construção"],
  ["47512", "Comércio Varejista Especializado de Equipamentos e Suprimentos de Informática"],
  ["47521", "Comércio Varejista Especializado de Equipamentos de Telefonia e Comunicação"],
  ["47539", "Comércio Varejista Especializado de Eletrodomésticos e Equipamentos de Áudio e Vídeo"],
  ["47547", "Comércio Varejista Especializado de Móveis, Colchoaria e Artigos de Iluminação"],
  ["47555", "Comércio Varejista Especializado de Tecidos e Artigos de Cama, Mesa e Banho"],
  ["47563", "Comércio Varejista Especializado de Instrumentos Musicais e Acessórios"],
  ["47571", "Comércio Varejista Especializado de Peças e Acessórios para Aparelhos Eletroeletrônicos para Uso Doméstico, Exceto Informática e Comunicação"],
  ["47598", "Comércio Varejista de Artigos de Uso Doméstico Não Especificados Anteriormente"],
  ["47610", "Comércio Varejista de Livros, Jornais, Revistas e Papelaria"],
  ["47628", "Comércio Varejista de Discos, Cds, Dvds e Fitas"],
  ["47636", "Comércio Varejista de Artigos Recreativos e Esportivos"],
  ["47717", "Comércio Varejista de Produtos Farmacêuticos para Uso Humano e Veterinário"],
  ["47725", "Comércio Varejista de Cosméticos, Produtos de Perfumaria e de Higiene Pessoal"],
  ["47733", "Comércio Varejista de Artigos Médicos e Ortopédicos"],
  ["47741", "Comércio Varejista de Artigos de Óptica"],
  ["47814", "Comércio Varejista de Artigos do Vestuário e Acessórios"],
  ["47822", "Comércio Varejista de Calçados e Artigos de Viagem"],
  ["47831", "Comércio Varejista de Joias e Relógios"],
  ["47849", "Comércio Varejista de Gás Liquefeito de Petróleo (glp)"],
  ["47857", "Comércio Varejista de Artigos Usados"],
  ["47890", "Comércio Varejista de Outros Produtos Novos Não Especificados Anteriormente"],
  ["47903", "Comércio Ambulante e Outros Tipos de Comércio Varejista"],
  ["49", "Transporte Terrestre"],
  ["49116", "Transporte Ferroviário de Carga"],
  ["49124", "Transporte Metroferroviário de Passageiros"],
  ["49213", "Transporte Rodoviário Coletivo de Passageiros, com Itinerário Fixo, Municipal e em Região Metropolitana"],
  ["49221", "Transporte Rodoviário Coletivo de Passageiros, com Itinerário Fixo, Intermunicipal, Interestadual e Internacional"],
  ["49230", "Transporte Rodoviário de Táxi"],
  ["49248", "Transporte Escolar"],
  ["49299", "Transporte Rodoviário Coletivo de Passageiros, sob Regime de Fretamento, e Outros Transportes Rodoviários Não Especificados Anteriormente"],
  ["49302", "Transporte Rodoviário de Carga"],
  ["49400", "Transporte Dutoviário"],
  ["49507", "Trens Turísticos, Teleféricos e Similares"],
  ["50", "Transporte Aquaviário"],
  ["50114", "Transporte Marítimo de Cabotagem"],
  ["50122", "Transporte Marítimo de Longo Curso"],
  ["50211", "Transporte por Navegação Interior de Carga"],
  ["50220", "Transporte por Navegação Interior de Passageiros em Linhas Regulares"],
  ["50301", "Navegação de Apoio"],
  ["50912", "Transporte por Navegação de Travessia"],
  ["50998", "Transportes Aquaviários Não Especificados Anteriormente"],
  ["51", "Transporte Aéreo"],
  ["51111", "Transporte Aéreo de Passageiros Regular"],
  ["51129", "Transporte Aéreo de Passageiros Não Regular"],
  ["51200", "Transporte Aéreo de Carga"],
  ["51307", "Transporte Espacial"],
  ["52", "Armazenamento e Atividades Auxiliares dos Transportes"],
  ["52117", "Armazenamento"],
  ["52125", "Carga e Descarga"],
  ["52214", "Concessionárias de Rodovias, Pontes, Túneis e Serviços Relacionados"],
  ["52222", "Terminais Rodoviários e Ferroviários"],
  ["52231", "Estacionamento de Veículos"],
  ["52290", "Atividades Auxiliares dos Transportes Terrestres Não Especificadas Anteriormente"],
  ["52311", "Gestão de Portos e Terminais"],
  ["52320", "Atividades de Agenciamento Marítimo"],
  ["52397", "Atividades Auxiliares dos Transportes Aquaviários Não Especificadas Anteriormente"],
  ["52401", "Atividades Auxiliares dos Transportes Aéreos"],
  ["52508", "Atividades Relacionadas À Organização do Transporte de Carga"],
  ["53", "Correio e Outras Atividades de Entrega"],
  ["53105", "Atividades de Correio"],
  ["53202", "Atividades de Malote e de Entrega"],
  ["55", "Alojamento"],
  ["55108", "Hotéis e Similares"],
  ["55906", "Outros Tipos de Alojamento Não Especificados Anteriormente"],
  ["56", "Alimentação"],
  ["56112", "Restaurantes e Outros Estabelecimentos de Serviços de Alimentação e Bebidas"],
  ["56121", "Serviços Ambulantes de Alimentação"],
  ["56201", "Serviços de Catering, Bufê e Outros Serviços de Comida Preparada"],
  ["58", "Edição e Edição Integrada À Impressão"],
  ["58115", "Edição de Livros"],
  ["58123", "Edição de Jornais"],
  ["58131", "Edição de Revistas"],
  ["58191", "Edição de Cadastros, Listas e de Outros Produtos Gráficos"],
  ["58212", "Edição Integrada À Impressão de Livros"],
  ["58221", "Edição Integrada À Impressão de Jornais"],
  ["58239", "Edição Integrada À Impressão de Revistas"],
  ["58298", "Edição Integrada À Impressão de Cadastros, Listas e de Outros Produtos Gráficos"],
  ["59", "Atividades Cinematográficas, Produção de Vídeos e de Programas de Televisão; Gravação de Som e Edição de Música"],
  ["59111", "Atividades de Produção Cinematográfica, de Vídeos e de Programas de Televisão"],
  ["59120", "Atividades de Pós-Produção Cinematográfica, de Vídeos e de Programas de Televisão"],
  ["59138", "Distribuição Cinematográfica, de Vídeo e de Programas de Televisão"],
  ["59146", "Atividades de Exibição Cinematográfica"],
  ["59201", "Atividades de Gravação de Som e de Edição de Música"],
  ["60", "Atividades de Rádio e de Televisão"],
  ["60101", "Atividades de Rádio"],
  ["60217", "Atividades de Televisão Aberta"],
  ["60225", "Programadoras e Atividades Relacionadas À Televisão por Assinatura"],
  ["61", "Telecomunicações"],
  ["61108", "Telecomunicações por Fio"],
  ["61205", "Telecomunicações sem Fio"],
  ["61302", "Telecomunicações por Satélite"],
  ["61418", "Operadoras de Televisão por Assinatura por Cabo"],
  ["61426", "Operadoras de Televisão por Assinatura por Micro-Ondas"],
  ["61434", "Operadoras de Televisão por Assinatura por Satélite"],
  ["61906", "Outras Atividades de Telecomunicações"],
  ["62", "Atividades dos Serviços de Tecnologia da Informação"],
  ["62015", "Desenvolvimento de Programas de Computador sob Encomenda"],
  ["62023", "Desenvolvimento e Licenciamento de Programas de Computador Customizáveis"],
  ["62031", "Desenvolvimento e Licenciamento de Programas de Computador Não Customizáveis"],
  ["62040", "Consultoria em Tecnologia da Informação"],
  ["62091", "Suporte Técnico, Manutenção e Outros Serviços em Tecnologia da Informação"],
  ["63", "Atividades de Prestação de Serviços de Informação"],
  ["63119", "Tratamento de Dados, Provedores de Serviços de Aplicação e Serviços de Hospedagem na Internet"],
  ["63194", "Portais, Provedores de Conteúdo e Outros Serviços de Informação na Internet"],
  ["63917", "Agências de Notícias"],
  ["63992", "Outras Atividades de Prestação de Serviços de Informação Não Especificadas Anteriormente"],
  ["64", "Atividades de Serviços Financeiros"],
  ["64107", "Banco Central"],
  ["64212", "Bancos Comerciais"],
  ["64221", "Bancos Múltiplos, com Carteira Comercial"],
  ["64239", "Caixas Econômicas"],
  ["64247", "Crédito Cooperativo"],
  ["64310", "Bancos Múltiplos, sem Carteira Comercial"],
  ["64328", "Bancos de Investimento"],
  ["64336", "Bancos de Desenvolvimento"],
  ["64344", "Agências de Fomento"],
  ["64352", "Crédito Imobiliário"],
  ["64361", "Sociedades de Crédito, Financiamento e Investimento - Financeiras"],
  ["64379", "Sociedades de Crédito ao Microempreendedor"],
  ["64387", "Bancos de Cambio e Outras Instituições de Intermediação Não Monetária"],
  ["64409", "Arrendamento Mercantil"],
  ["64506", "Sociedades de Capitalização"],
  ["64611", "Holdings de Instituições Financeiras"],
  ["64620", "Holdings de Instituições Não Financeiras"],
  ["64638", "Outras Sociedades de Participação, Exceto Holdings"],
  ["64701", "Fundos de Investimento"],
  ["64913", "Sociedades de Fomento Mercantil - Factoring"],
  ["64921", "Securitização de Créditos"],
  ["64930", "Administração de Consórcios para Aquisição de Bens e Direitos"],
  ["64999", "Outras Atividades de Serviços Financeiros Não Especificadas Anteriormente"],
  ["65", "Seguros, Resseguros, Previdência Complementar e Planos de Saúde"],
  ["65111", "Seguros de Vida"],
  ["65120", "Seguros Não Vida"],
  ["65201", "Seguros-Saúde"],
  ["65308", "Resseguros"],
  ["65413", "Previdência Complementar Fechada"],
  ["65421", "Previdência Complementar Aberta"],
  ["65502", "Planos de Saúde"],
  ["66", "Atividades Auxiliares dos Serviços Financeiros, Seguros, Previdência Complementar e Planos de Saúde"],
  ["66118", "Administração de Bolsas e Mercados de Balcão Organizados"],
  ["66126", "Atividades de Intermediários em Transações de Títulos, Valores Mobiliários e Mercadorias"],
  ["66134", "Administração de Cartões de Crédito"],
  ["66193", "Atividades Auxiliares dos Serviços Financeiros Não Especificadas Anteriormente"],
  ["66215", "Avaliação de Riscos e Perdas"],
  ["66223", "Corretores e Agentes de Seguros, de Planos de Previdência Complementar e de Saúde"],
  ["66291", "Atividades Auxiliares dos Seguros, da Previdência Complementar e dos Planos de Saúde Não Especificadas Anteriormente"],
  ["66304", "Atividades de Administração de Fundos por Contrato ou Comissão"],
  ["68", "Atividades Imobiliárias"],
  ["68102", "Atividades Imobiliárias de Imóveis Próprios"],
  ["68218", "Intermediação na Compra, Venda e Aluguel de Imóveis"],
  ["68226", "Gestão e Administração da Propriedade Imobiliária"],
  ["69", "Atividades Jurídicas, de Contabilidade e de Auditoria"],
  ["69117", "Atividades Jurídicas, Exceto Cartórios"],
  ["69125", "Cartórios"],
  ["69206", "Atividades de Contabilidade, Consultoria e Auditoria Contábil e Tributária"],
  ["70", "Atividades de Sedes de Empresas e de Consultoria em Gestão Empresarial"],
  ["70107", "Sedes de Empresas e Unidades Administrativas Locais"],
  ["70204", "Atividades de Consultoria em Gestão Empresarial"],
  ["71", "Serviços de Arquitetura e Engenharia; Testes e Análises Técnicas"],
  ["71111", "Serviços de Arquitetura"],
  ["71120", "Serviços de Engenharia"],
  ["71197", "Atividades Técnicas Relacionadas À Arquitetura e Engenharia"],
  ["71201", "Testes e Análises Técnicas"],
  ["72", "Pesquisa e Desenvolvimento Científico"],
  ["72100", "Pesquisa e Desenvolvimento Experimental em Ciências Físicas e Naturais"],
  ["72207", "Pesquisa e Desenvolvimento Experimental em Ciências Sociais e Humanas"],
  ["73", "Publicidade e Pesquisa de Mercado"],
  ["73114", "Agências de Publicidade"],
  ["73122", "Agenciamento de Espaços para Publicidade, Exceto em Veículos de Comunicação"],
  ["73190", "Atividades de Publicidade Não Especificadas Anteriormente"],
  ["73203", "Pesquisas de Mercado e de Opinião Pública"],
  ["74", "Outras Atividades Profissionais, Científicas e Técnicas"],
  ["74102", "Design e Decoração de Interiores"],
  ["74200", "Atividades Fotográficas e Similares"],
  ["74901", "Atividades Profissionais, Científicas e Técnicas Não Especificadas Anteriormente"],
  ["75", "Atividades Veterinárias"],
  ["75001", "Atividades Veterinárias"],
  ["77", "Aluguéis Não-Imobiliários e Gestão de Ativos Intangíveis Não-Financeiros"],
  ["77110", "Locação de Automóveis sem Condutor"],
  ["77195", "Locação de Meios de Transporte, Exceto Automóveis, sem Condutor"],
  ["77217", "Aluguel de Equipamentos Recreativos e Esportivos"],
  ["77225", "Aluguel de Fitas de Vídeo, Dvds e Similares"],
  ["77233", "Aluguel de Objetos do Vestuário, Joias e Acessórios"],
  ["77292", "Aluguel de Objetos Pessoais e Domésticos Não Especificados Anteriormente"],
  ["77314", "Aluguel de Máquinas e Equipamentos Agrícolas sem Operador"],
  ["77322", "Aluguel de Máquinas e Equipamentos para Construção sem Operador"],
  ["77331", "Aluguel de Máquinas e Equipamentos para Escritórios"],
  ["77390", "Aluguel de Máquinas e Equipamentos Não Especificados Anteriormente"],
  ["77403", "Gestão de Ativos Intangíveis Não Financeiros"],
  ["78", "Seleção, Agenciamento e Locação de Mão-de-Obra"],
  ["78108", "Seleção e Agenciamento de Mão de Obra"],
  ["78205", "Locação de Mão de Obra Temporária"],
  ["78302", "Fornecimento e Gestão de Recursos Humanos para Terceiros"],
  ["79", "Agências de Viagens, Operadores Turísticos e Serviços de Reservas"],
  ["79112", "Agências de Viagens"],
  ["79121", "Operadores Turísticos"],
  ["79902", "Serviços de Reservas e Outros Serviços de Turismo Não Especificados Anteriormente"],
  ["80", "Atividades de Vigilância, Segurança e Investigação"],
  ["80111", "Atividades de Vigilância e Segurança Privada"],
  ["80129", "Atividades de Transporte de Valores"],
  ["80200", "Atividades de Monitoramento de Sistemas de Segurança"],
  ["80307", "Atividades de Investigação Particular"],
  ["81", "Serviços para Edifícios e Atividades Paisagísticas"],
  ["81117", "Serviços Combinados para Apoio a Edifícios, Exceto Condomínios Prediais"],
  ["81125", "Condomínios Prediais"],
  ["81214", "Limpeza em Prédios e em Domicílios"],
  ["81222", "Imunização e Controle de Pragas Urbanas"],
  ["81290", "Atividades de Limpeza Não Especificadas Anteriormente"],
  ["81303", "Atividades Paisagísticas"],
  ["82", "Serviços de Escritório, de Apoio Administrativo e Outros Serviços Prestados Principalmente Às Empresas"],
  ["82113", "Serviços Combinados de Escritório e Apoio Administrativo"],
  ["82199", "Fotocópias, Preparação de Documentos e Outros Serviços Especializados de Apoio Administrativo"],
  ["82202", "Atividades de Teleatendimento"],
  ["82300", "Atividades de Organização de Eventos, Exceto Culturais e Esportivos"],
  ["82911", "Atividades de Cobranças e Informações Cadastrais"],
  ["82920", "Envasamento e Empacotamento sob Contrato"],
  ["82997", "Atividades de Serviços Prestados Principalmente Às Empresas Não Especificadas Anteriormente"],
  ["84", "Administração Pública, Defesa e Seguridade Social"],
  ["84116", "Administração Pública em Geral"],
  ["84124", "Regulação das Atividades de Saúde, Educação, Serviços Culturais e Outros Serviços Sociais"],
  ["84132", "Regulação das Atividades Econômicas"],
  ["84213", "Relações Exteriores"],
  ["84221", "Defesa"],
  ["84230", "Justiça"],
  ["84248", "Segurança e Ordem Pública"],
  ["84256", "Defesa Civil"],
  ["84302", "Seguridade Social Obrigatória"],
  ["85", "Educação"],
  ["85112", "Educação Infantil - Creche"],
  ["85121", "Educação Infantil - Pré-Escola"],
  ["85139", "Ensino Fundamental"],
  ["85201", "Ensino Médio"],
  ["85317", "Educação Superior - Graduação"],
  ["85325", "Educação Superior - Graduação e Pós-Graduação"],
  ["85333", "Educação Superior - Pós-Graduação e Extensão"],
  ["85414", "Educação Profissional de Nível Técnico"],
  ["85422", "Educação Profissional de Nível Tecnológico"],
  ["85503", "Atividades de Apoio À Educação"],
  ["85911", "Ensino de Esportes"],
  ["85929", "Ensino de Arte e Cultura"],
  ["85937", "Ensino de Idiomas"],
  ["85996", "Atividades de Ensino Não Especificadas Anteriormente"],
  ["86", "Atividades de Atenção À Saúde Humana"],
  ["86101", "Atividades de Atendimento Hospitalar"],
  ["86216", "Serviços Móveis de Atendimento a Urgências"],
  ["86224", "Serviços de Remoção de Pacientes, Exceto os Serviços Móveis de Atendimento a Urgências"],
  ["86305", "Atividades de Atenção Ambulatorial Executadas por Médicos e Odontólogos"],
  ["86402", "Atividades de Serviços de Complementação Diagnóstica e Terapêutica"],
  ["86500", "Atividades de Profissionais da Área de Saúde, Exceto Médicos e Odontólogos"],
  ["86607", "Atividades de Apoio À Gestão de Saúde"],
  ["86909", "Atividades de Atenção À Saúde Humana Não Especificadas Anteriormente"],
  ["87", "Atividades de Atenção À Saúde Humana Integradas com Assistência Social, Prestadas em Residências Coletivas e Particulares"],
  ["87115", "Atividades de Assistência a Idosos, Deficientes Físicos, Imunodeprimidos e Convalescentes Prestadas em Residências Coletivas e Particulares"],
  ["87123", "Atividades de Fornecimento de Infraestrutura de Apoio e Assistência a Paciente no Domicílio"],
  ["87204", "Atividades de Assistência Psicossocial e À Saúde a Portadores de Distúrbios Psíquicos, Deficiência Mental e Dependência Química"],
  ["87301", "Atividades de Assistência Social Prestadas em Residências Coletivas e Particulares"],
  ["88", "Serviços de Assistência Social sem Alojamento"],
  ["88006", "Serviços de Assistência Social sem Alojamento"],
  ["90", "Atividades Artísticas, Criativas e de Espetáculos"],
  ["90019", "Artes Cênicas, Espetáculos e Atividades Complementares"],
  ["90027", "Criação Artística"],
  ["90035", "Gestão de Espaços para Artes Cênicas, Espetáculos e Outras Atividades Artísticas"],
  ["91", "Atividades Ligadas ao Patrimônio Cultural e Ambiental"],
  ["91015", "Atividades de Bibliotecas e Arquivos"],
  ["91023", "Atividades de Museus e de Exploração, Restauração Artística e Conservação de Lugares e Prédios Históricos e Atrações Similares"],
  ["91031", "Atividades de Jardins Botânicos, Zoológicos, Parques Nacionais, Reservas Ecológicas e Áreas de Proteção Ambiental"],
  ["92", "Atividades de Exploração de Jogos de Azar e Apostas"],
  ["92003", "Atividades de Exploração de Jogos de Azar e Apostas"],
  ["93", "Atividades Esportivas e de Recreação e Lazer"],
  ["93115", "Gestão de Instalações de Esportes"],
  ["93123", "Clubes Sociais, Esportivos e Similares"],
  ["93131", "Atividades de Condicionamento Físico"],
  ["93191", "Atividades Esportivas Não Especificadas Anteriormente"],
  ["93212", "Parques de Diversão e Parques Temáticos"],
  ["93298", "Atividades de Recreação e Lazer Não Especificadas Anteriormente"],
  ["94", "Atividades de Organizações Associativas"],
  ["94111", "Atividades de Organizações Associativas Patronais e Empresariais"],
  ["94120", "Atividades de Organizações Associativas Profissionais"],
  ["94201", "Atividades de Organizações Sindicais"],
  ["94308", "Atividades de Associações de Defesa de Direitos Sociais"],
  ["94910", "Atividades de Organizações Religiosas"],
  ["94928", "Atividades de Organizações Políticas"],
  ["94936", "Atividades de Organizações Associativas Ligadas À Cultura e À Arte"],
  ["94995", "Atividades Associativas Não Especificadas Anteriormente"],
  ["95", "Reparação e Manutenção de Equipamentos de Informática e Comunicação e de Objetos Pessoais e Domésticos"],
  ["95118", "Reparação e Manutenção de Computadores e de Equipamentos Periféricos"],
  ["95126", "Reparação e Manutenção de Equipamentos de Comunicação"],
  ["95215", "Reparação e Manutenção de Equipamentos Eletroeletrônicos de Uso Pessoal e Doméstico"],
  ["95291", "Reparação e Manutenção de Objetos e Equipamentos Pessoais e Domésticos Não Especificados Anteriormente"],
  ["96", "Outras Atividades de Serviços Pessoais"],
  ["96017", "Lavanderias, Tinturarias e Toalheiros"],
  ["96025", "Cabeleireiros e Outras Atividades de Tratamento de Beleza"],
  ["96033", "Atividades Funerárias e Serviços Relacionados"],
  ["96092", "Atividades de Serviços Pessoais Não Especificadas Anteriormente"],
  ["97", "Serviços Domésticos"],
  ["97005", "Serviços Domésticos"],
  ["99", "Organismos Internacionais e Outras Instituições Extraterritoriais"],
  ["99008", "Organismos Internacionais e Outras Instituições Extraterritoriais"],
];
